### ISSUE TITLE
Could not support MySQL 8.0.11

### ISSUE THREAD

**Issue by kn007** [nginxinc/nginx-amplify-agent#102]
MySQL 8.0.11 GA now, but the agent could not get the data.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/amplify/agent/collectors/abstract.py", line 129, in collect
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/amplify/ext/mysql/collectors/metrics.py", line 65, in mysql_status
    c = pymysql.connect(**self.object.connection_args)  # these are coming from agent config for now
  File "/usr/lib/python2.7/site-packages/amplify/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/amplify/pymysql/connections.py", line 706, in __init__
    self.connect()
  File "/usr/lib/python2.7/site-packages/amplify/pymysql/connections.py", line 931, in connect
    self._get_server_information()
  File "/usr/lib/python2.7/site-packages/amplify/pymysql/connections.py", line 1269, in _get_server_information
    self.server_charset = charset_by_id(lang).name
  File "/usr/lib/python2.7/site-packages/amplify/pymysql/charset.py", line 38, in by_id
    return self._by_id[id]
KeyError: 255
```

**Comment by akamoroz** [comment]
Thank you @kn007 for reporting this issue.
We will fix it as soon as we can.

Also, we will be appreciated if you fix if and send Pull Request. We are still a small team here and welcome for any help.

Thanks!

**Comment by Asuquo12** [comment]
I am having a similar problem monitoring MySQL 8.0 on the same host using Amplify. Any update on this challenge?
