### ISSUE TITLE
OSError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by Donatui** [nginxinc/nginx-amplify-agent#107]
Agent fails to read SSL cerfiticates, but premissions are good (www-data)

```
2018-05-02 15:49:04,462 [1050] nginx_config failed to stat /etc/letsencrypt/live/sertifikatai/ do to OSError
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/agent/objects/nginx/config/parser.py", line 70, in get_filesystem_info
    info = os.stat(path)
OSError: [Errno 13] Permission denied: '/etc/letsencrypt/live/sertifikatai/'
2018-05-02 15:49:04,462 [1050] nginx_config failed to read /etc/letsencrypt/live/sertifikatai/ due to: OSError
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/agent/objects/nginx/config/parser.py", line 222, in _add_directory
    scandir.scandir(dirname)
OSError: [Errno 13] Permission denied: '/etc/letsencrypt/live/sertifikatai/'
2018-05-02 15:49:04,462 [1050] nginx_config failed to stat /etc/letsencrypt/live/sertifikatai/fullchain.pem do to OSError
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/agent/objects/nginx/config/parser.py", line 70, in get_filesystem_info
    info = os.stat(path)
OSError: [Errno 13] Permission denied: '/etc/letsencrypt/live/sertifikatai/fullchain.pem'
2018-05-02 15:49:04,463 [1050] nginx_config failed to stat /etc/letsencrypt/live/sertifikatai/fullchain.pem do to OSError
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/agent/objects/nginx/config/parser.py", line 70, in get_filesystem_info
    info = os.stat(path)
OSError: [Errno 13] Permission denied: '/etc/letsencrypt/live/sertifikatai/fullchain.pem'
2018-05-02 15:49:04,463 [1050] nginx_config failed to stat /etc/letsencrypt/live/sertifikatai/fullchain.pem do to OSError
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/agent/objects/nginx/config/parser.py", line 70, in get_filesystem_info
    info = os.stat(path)
OSError: [Errno 13] Permission denied: '/etc/letsencrypt/live/sertifikatai/fullchain.pem'
2018-05-02 15:49:04,463 [1050] nginx_config failed to stat /etc/letsencrypt/live/sertifikatai/fullchain.pem do to OSError
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/agent/objects/nginx/config/parser.py", line 70, in get_filesystem_info
    info = os.stat(path)
OSError: [Errno 13] Permission denied: '/etc/letsencrypt/live/sertifikatai/fullchain.pem'
2018-05-02 15:49:04,464 [1050] nginx_config failed to stat /etc/letsencrypt/live/sertifikatai/fullchain.pem do to OSError
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/agent/objects/nginx/config/parser.py", line 70, in get_filesystem_info
    info = os.stat(path)
OSError: [Errno 13] Permission denied: '/etc/letsencrypt/live/sertifikatai/fullchain.pem'
```

```
root@area51:/var/log/amplify-agent# ls -la /etc/letsencrypt/live/sertifikatai/
total 12
drwxr-xr-x 2 www-data www-data 4096 Apr 29 00:33 .
drwx------ 3 root     root     4096 Feb 27 17:04 ..
-rw-r--r-- 1 www-data www-data  543 Feb 27 16:12 README
lrwxrwxrwx 1 www-data www-data   47 Apr 29 00:33 cert.pem -> /etc/letsencrypt/archive/sertifikatai/cert2.pem
lrwxrwxrwx 1 www-data www-data   48 Apr 29 00:33 chain.pem -> /etc/letsencrypt/archive/sertifikatai/chain2.pem
lrwxrwxrwx 1 www-data www-data   52 Apr 29 00:33 fullchain.pem -> /etc/letsencrypt/archive/sertifikatai/fullchain2.pem
lrwxrwxrwx 1 www-data www-data   50 Apr 29 00:33 privkey.pem -> /etc/letsencrypt/archive/sertifikatai/privkey2.pem
```

```
root@area51:/var/log/amplify-agent# ls -la /etc/letsencrypt/archive/sertifikatai/
total 40
drwxr-xr-x 2 www-data www-data 4096 Apr 29 00:33 .
drwx------ 3 root     root     4096 Feb 27 17:11 ..
-rw-r--r-- 1 www-data www-data 1964 Feb 27 16:12 cert1.pem
-rw-r--r-- 1 www-data www-data 2317 Apr 29 00:33 cert2.pem
-rw-r--r-- 1 www-data www-data 1647 Feb 27 16:12 chain1.pem
-rw-r--r-- 1 www-data www-data 1647 Apr 29 00:33 chain2.pem
-rw-r--r-- 1 www-data www-data 3611 Feb 27 16:12 fullchain1.pem
-rw-r--r-- 1 www-data www-data 3964 Apr 29 00:33 fullchain2.pem
-rw-r--r-- 1 www-data www-data 1704 Feb 27 16:12 privkey1.pem
-rw-r--r-- 1 www-data www-data 1704 Apr 29 00:33 privkey2.pem
```

**Comment by gshulegaard** [comment]
Can you send the the `ps` output of `ps -elf | grep amplify-agent` and `ps -elf | grep nginx`?

**Comment by Donatui** [comment]
```
root@area51:~# ps -elf | grep amplify-agent
1 S www-data  1050     1  1  80   0 - 47511 ep_pol May02 ?        00:10:44 amplify-agent
0 S root     11407 11338  0  80   0 -  2763 pipe_w 08:11 pts/0    00:00:00 grep amplify-agent
```

```
root@area51:~# ps -elf | grep nginx
5 S root       930     1  0  80   0 - 24488 rt_sig May02 ?        00:00:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
5 S www-data   931   930  0  80   0 - 24658 ep_pol May02 ?        00:00:21 nginx: worker process
5 S www-data   932   930  0  80   0 - 24765 ep_pol May02 ?        00:00:21 nginx: worker process
5 S www-data   933   930  0  80   0 - 24488 ep_pol May02 ?        00:00:00 nginx: cache manager process
0 S root     11534 11338  0  80   0 -  2763 pipe_w 08:11 pts/0    00:00:00 grep nginx
```

**Comment by Donatui** [comment]
I tried, reported some other errors, got luck with responce for 1 day, but then no answer to other problems... Seems no one is there.

**Comment by gshulegaard** [comment]
Ah, well may already have a support ticket outstanding.  I can't link this issue to one in our support queue without PII, but I'll try to remember to link it if I see it.  Thanks for taking the time to report!

**Comment by akamoroz** [comment]
I was not able to manage tickets for the last two days.
Sorry for that, @Donatui.

I've already created the ticket for this case to our support team, pls check out your mailbox.

**Comment by locvfx** [comment]
chown -R nginx:nginx /etc/letsencrypt

Please note www-data is the actual user of your Nginx web server
You can find it using this command : cat /etc/passwd and look for "/var/lib/nginx:/sbin/nologin"
example : **nginx:x:997:995:Nginx web server:/var/lib/nginx:/sbin/nologin**
