### ISSUE TITLE
supervisor uncaught exception during run time

### ISSUE THREAD

**Issue by draskolnikova** [nginxinc/nginx-amplify-agent#11]
I've update to 0.25-2, after restarting service got this error.
```
Traceback (most recent call last):
  File "/usr/bin/nginx-amplify-agent.py", line 103, in <module>
    daemon_runner.do_action()
  File "/usr/lib/python2.7/site-packages/amplify/daemon/runner.py", line 267, in do_action
    func(self)
  File "/usr/lib/python2.7/site-packages/amplify/daemon/runner.py", line 186, in _start
    self.app.run()
  File "/usr/lib/python2.7/site-packages/amplify/agent/supervisor.py", line 105, in run
    time.sleep(5.0)
  File "/usr/lib/python2.7/site-packages/amplify/gevent/hub.py", line 82, in sleep
    hub.wait(loop.timer(seconds, ref=ref))
  File "/usr/lib/python2.7/site-packages/amplify/gevent/hub.py", line 348, in wait
    result = waiter.get()
  File "/usr/lib/python2.7/site-packages/amplify/gevent/hub.py", line 575, in get
    return self.hub.switch()
  File "/usr/lib/python2.7/site-packages/amplify/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
AttributeError: 'Greenlet' object has no attribute 'flush_metrics'
```

And the stub_status said that they failed to check it.
```
2015-12-05 08:52:33,338 [56720] supervisor failed to check stub_status url http://<ip_addr>:80/nginx_status
2015-12-05 08:52:33,340 [56720] supervisor failed to check stub_status url https://<ip_addr>:80/nginx_status
```

Note: The ip addr is public static ip and was allowed on the configuration.
```
[..snip..]
        location /nginx_status {
                stub_status on;
                access_log   off;
                allow <ip_addr>/23;
                allow 127.0.0.1;
                deny all;
        }
[..snip..]
```

For sure, I tried to check the response using cURL.
```
[root@loadbalancer ~]# curl http://<ip_addr>:80/nginx_status
Active connections: 2 
server accepts handled requests
 89336 89336 114315 
Reading: 0 Writing: 1 Waiting: 1 
```

I'm using `Cent OS 7` and `nginx-plus-r7`.

**Comment by dedm** [comment]
1. AttributeError: 'Greenlet' object. 
That's just a debug output. We will fix it in the next version.

2. Stub status problem. 
I can't tell why stub status discovery failed, because I need the whole nginx config. Can you privately send it to me?

**Comment by draskolnikova** [comment]
@dedm sure you can have my whole nginx config, could you gimme your mail address?

**Comment by dedm** [comment]
@draskolnikova I sent you that information via intercom and email.
