### ISSUE TITLE
Failure to gather MySQL metrics

### ISSUE THREAD

**Issue by dvershinin** [nginxinc/nginx-amplify-agent#116]
MySQL version: Server version: 5.6.39 MySQL Community Server (GPL)
Python version: 2.6.6
OS: CentOS release 6.10 (Final)

I've configured MySQL user for amplify agent, made sure it can read global metric (verified on the command line), set correct path to MySQL socket file, running amplify agent as root user, but...:

```
mysql_meta failed to connect to MySQLd due to TypeError
2018-07-27 16:34:43,607 [30291] mysql_meta additional info:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/amplify/ext/mysql/objects.py", line 82, in connect
    return pymysql.connect(**conn_kwargs)
  File "/usr/lib/python2.6/site-packages/amplify/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/amplify/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/usr/lib/python2.6/site-packages/amplify/pymysql/connections.py", line 935, in connect
    self._get_server_information()
  File "/usr/lib/python2.6/site-packages/amplify/pymysql/connections.py", line 1249, in _get_server_information
    packet = self._read_packet()
  File "/usr/lib/python2.6/site-packages/amplify/pymysql/connections.py", line 991, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/lib/python2.6/site-packages/amplify/pymysql/connections.py", line 1025, in _read_bytes
    data = self._rfile.read(num_bytes)
  File "/usr/lib64/python2.6/io.py", line 940, in read
    return self._read_unlocked(n)
  File "/usr/lib64/python2.6/io.py", line 974, in _read_unlocked
    chunk = self.raw.read(wanted)
  File "/usr/lib64/python2.6/io.py", line 591, in read
    n = self.readinto(b)
  File "/usr/lib/python2.6/site-packages/amplify/pymysql/_socketio.py", line 59, in readinto
    return self._sock.recv_into(b)
TypeError: recv_into() argument 1 must be pinned buffer, not bytearray
```

**Comment by akamoroz** [comment]
Hello @dvershinin,
this issue requires some investigation. Creating a ticket in our support queue. Pls check your mailbox.
