### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'definition'

### ISSUE THREAD

**Issue by vadamlyuk** [nginxinc/nginx-amplify-agent#14]
I have the following error in amplify agent log-file:

2016-03-22 11:31:12,584 [4172] bridge failed
Traceback (most recent call last):
  File "/usr/local/src/nginx-amplify/nginx-amplify-agent/amplify/agent/bridge.py", line 49, in run
    self.flush_all()
  File "/usr/local/src/nginx-amplify/nginx-amplify-agent/amplify/agent/bridge.py", line 73, in flush_all
    self.payload['meta'].append(self.flush_meta())
  File "/usr/local/src/nginx-amplify/nginx-amplify-agent/amplify/agent/bridge.py", line 105, in flush_meta
    return self._flush(container=context.metad)
  File "/usr/local/src/nginx-amplify/nginx-amplify-agent/amplify/agent/bridge.py", line 126, in _flush
    root = {'object': context.top_object.definition}
AttributeError: 'NoneType' object has no attribute 'definition'

But this error appears only in case nginx stub_status page is enabled.

Unfortunatly, I'm not familiar with python and for me is difficult to find the source of problem.

**Comment by dedm** [comment]
Sorry for the delay.

Could you run this script https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/collect-env.sh and send me the output?

**Comment by dedm** [comment]
we don't support openSUSE, but we will investigate this issue

**Comment by tburazin** [comment]
I also got the bridge failed error after enabling stub_status, running CentOS 6.7.
Amplify shows Req and Conn but not Errors, HTTP Version, Traffic, Disk Buffered, Request and Response Time.

Full error message:
bridge failed                                                                                                 
Traceback (most recent call last):                                                                                                             
  File "/usr/lib/python2.6/site-packages/amplify/agent/bridge.py", line 46, in run                                                             
    self.flush_all()                                                                                                                           
  File "/usr/lib/python2.6/site-packages/amplify/agent/bridge.py", line 63, in flush_all                                                       
    self.payload['meta'].append(self.flush_meta())                                                                                             
  File "/usr/lib/python2.6/site-packages/amplify/agent/bridge.py", line 96, in flush_meta                                                      
    return self._flush(container=context.metad)                                                                                                
  File "/usr/lib/python2.6/site-packages/amplify/agent/bridge.py", line 117, in _flush                                                         
    root = {'object': context.top_object.definition}                                                                                           
AttributeError: 'NoneType' object has no attribute 'definition'

**Comment by dedm** [comment]
@tburazin 

To investigate this bug we need a little bit more debug information. 

Please, do the following things: 
1. enable debug mode (https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#logging) and restart amplify-agent. Wait for a minute or two and then send me /var/log/amplify-agent/agent.log via email
2. run this script https://github.com/nginxinc/nginx-amplify-agent/blob/master/packages/collect-env.sh and also send me the output via email 

Many thanks in advance!

**Comment by tburazin** [comment]
@dedm I've made the files, I'm just having difficulty finding your email...

**Comment by dedm** [comment]
@tburazin dedm (at) nginx.com

**Comment by tburazin** [comment]
@dedm mail sent, thanks
