### ISSUE TITLE
Linux 4.x: sys_metrics failed to collect: disk_io_counters raised ValueError

### ISSUE THREAD

**Issue by janvitos** [nginxinc/nginx-amplify-agent#159]
Hi,

So I'm using CentOS 8 and successfully compiled and installed the NGINX Amplify Agent without too much trouble, but I noticed disk stats were not showing up under System -> Disk Latency, Disk IOPS
 and Disk I/O. After changing the log level to debug in agent.conf and looking at the agent.log file, I noticed the following error:
```
sys_metrics sys_metrics failed to collect: disk_io_counters raised ValueError

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.7.0-py2.7.egg/amplify/agent/collectors/abstract.py", line 129, in collect
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.7.0-py2.7.egg/amplify/agent/collectors/system/metrics.py", line 131, in disk_io_counters
    disk_counters = {'__all__': psutil.disk_io_counters(perdisk=False)}
  File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.7.0-py2.7.egg/amplify/psutil/__init__.py", line 1803, in disk_io_counters
    rawdict = _psplatform.disk_io_counters()
  File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.7.0-py2.7.egg/amplify/psutil/_pslinux.py", line 819, in disk_io_counters
    raise ValueError("not sure how to interpret line %r" % line)
```
After further investigation, I noticed that with Linux 2.6+, /proc/diskstats returns 14 fields, but with Linux 4.18, there are 18 fields returned in total. So I went ahead and modified _pslinux.py to add the new Linux version and appropriate fields_len of 18.

This fixed the issue and I am now getting disk stats in the Amplify Agent.

**Comment by defanator** [comment]
@janvitos this is related to old `psutil` module, latest agent package version (1.7.0-5) has recent `psutil` that shouldn't produce such errors. Also see #152.
