### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by xvybihal** [nginxinc/nginx-amplify-agent#17]
At one box with CentOS7, I am having this issue, that I am not able to resolve (yet).

`2016-04-26 09:01:25,578 [50497] supervisor uncaught exception during run time
Traceback (most recent call last):
  File "/usr/bin/nginx-amplify-agent.py", line 103, in <module>
    daemon_runner.do_action()
  File "/usr/lib/python2.7/site-packages/amplify/daemon/runner.py", line 267, in do_action
    func(self)
  File "/usr/lib/python2.7/site-packages/amplify/daemon/runner.py", line 186, in _start
    self.app.run()
  File "/usr/lib/python2.7/site-packages/amplify/agent/supervisor.py", line 109, in run
    container._discover_objects()
  File "/usr/lib/python2.7/site-packages/amplify/agent/containers/abstract.py", line 56, in _discover_objects
    self.discover_objects()
  File "/usr/lib/python2.7/site-packages/amplify/agent/containers/nginx/container.py", line 43, in discover_objects
    new_obj = NginxObject(definition=definition, data=data)
  File "/usr/lib/python2.7/site-packages/amplify/agent/containers/nginx/object.py", line 47, in __init__
    self.config.full_parse()
  File "/usr/lib/python2.7/site-packages/amplify/agent/nginx/config/config.py", line 76, in full_parse
    self.__recursive_search(subtree=self.parser.simplify())
  File "/usr/lib/python2.7/site-packages/amplify/agent/nginx/config/config.py", line 204, in __recursive_search
    self.__recursive_search(subtree=value, ctx=ctx)
  File "/usr/lib/python2.7/site-packages/amplify/agent/nginx/config/config.py", line 164, in __recursive_search
    addr, port = self.__parse_listen(listen_first_part)
  File "/usr/lib/python2.7/site-packages/amplify/agent/nginx/config/config.py", line 306, in __parse_listen
    bracket, port = addr_port_parts[1].split(':')
ValueError: need more than 1 value to unpack
`

Agent installed just fine, same as on any other CentOS7 box, no issues. Ideas?

**Comment by dedm** [comment]
Hi! Looks like a bug in the config parser module.

To work on it we need your nginx config file. Would you mind sending it to me?

**Comment by xvybihal** [comment]
I tampered little bit with the generated config, but still no luck. Here is the conf I am using now: https://pastee.org/vh32e

**Comment by dedm** [comment]
Oh, I'm sorry, I was talking about nginx.conf file - the config file for nginx, not for amplify-agent. 

You can send it directly to me via email.
