### ISSUE TITLE
Failed to push data due to TypeError

### ISSUE THREAD

**Issue by howdu** [nginxinc/nginx-amplify-agent#216]
Setting up a new server but amplify appears to randomly stop reporting.

Looking at my log bridge_manager appears to work and then stop working. 

Also mysql is not appearing even though the extension is enabled, mysql user created and verified the password is correct viewing the global stats. 

2022-01-19 11:18:43,251 [784010] supervisor failed to push data due to TypeError
2022-01-19 11:18:43,254 [784010] supervisor agent stopped, version=1.8.0-1 pid=784010 uuid=d4adc6e0423d5fdc87b0a4e19493d581
2022-01-19 11:18:44,316 [844835] MainThread performing configtest check...
2022-01-19 11:18:44,980 [844835] MainThread [b53a0f0a73246159f1ae30773d56326c] post https://receiver.amplify.nginx.com:443/1.4/3d6498c21b1730b9bfede9bb2bab9f82/agent/ 200 10 5 0.663
2022-01-19 11:18:44,980 [844835] MainThread config file is ok!
2022-01-19 11:18:46,399 [844850] supervisor [b7670207b9018d68cfa17972384887e2] post https://receiver.amplify.nginx.com:443/1.4/3d6498c21b1730b9bfede9bb2bab9f82/agent/ 200 101 5 0.682
2022-01-19 11:18:52,555 [844850] supervisor agent started, version=1.8.0-1 pid=844850 uuid=d4adc6e0423d5fdc87b0a4e19493d581 hostname=example.com
2022-01-19 11:18:52,850 [844850] supervisor ssl certificate found /etc/letsencrypt/live/example.com/fullchain.pem
2022-01-19 11:18:52,984 [844850] supervisor ssl certificate found /etc/nginx/ssl/nginx.crt
2022-01-19 11:19:47,181 [844850] bridge_manager [aa6095dd2525680c99b2725d64ce918c] post https://receiver.amplify.nginx.com:443/1.4/3d6498c21b1730b9bfede9bb2bab9f82/update/ 202 2210 0 0.612
2022-01-19 11:20:46,429 [844850] supervisor [109e86d3cb1ce81be7a01b2d793447dd] post https://receiver.amplify.nginx.com:443/1.4/3d6498c21b1730b9bfede9bb2bab9f82/agent/ 200 100 5 0.220
2022-01-19 11:20:47,222 [844850] bridge_manager failed to push data due to TypeError
2022-01-19 11:22:47,286 [844850] bridge_manager failed to push data due to TypeError
2022-01-19 11:22:49,672 [844850] supervisor [3733c8f8bec7fb6891969bbab505c8bd] post https://receiver.amplify.nginx.com:443/1.4/3d6498c21b1730b9bfede9bb2bab9f82/agent/ 200 100 5 0.677
2022-01-19 11:24:47,344 [844850] bridge_manager failed to push data due to TypeError
2022-01-19 11:24:52,874 [844850] supervisor [ca63f2e41e0143bb3d044426a28bf201] post https://receiver.amplify.nginx.com:443/1.4/3d6498c21b1730b9bfede9bb2bab9f82/agent/ 200 100 5 0.676
2022-01-19 11:24:53,531 [844850] nginx_config ssl certificate found /etc/letsencrypt/live/eample.com/fullchain.pem
2022-01-19 11:24:53,730 [844850] nginx_config ssl certificate found /etc/nginx/ssl/nginx.crt 

[credentials]
api_key = 123
hostname =
uuid = d4adc6e0423d5fdc87b0a4e19493d581
imagename =
store_uuid = False

[agent]
launchers =

[nginx]

[proxies]
https =

[cloud]
api_url = https://receiver.amplify.nginx.com:443/1.4
api_timeout = 5.0

[extensions]
phpfpm = True
mysql = True

[mysql]
unix_socket = /var/run/mysqld/mysqld.sock
user = amplify-agent
password = password123
remote = False

[listeners]
keys = syslog-default

[listener_syslog-default]
address =

[loggers]
keys = root,devnull,agent-default

[handlers]
keys = root,devnull,agent-default

[formatters]
keys = simpleFormatter

[formatter_simpleFormatter]
format = %(asctime)s [%(process)d] %(threadName)s %(message)s
datefmt =

[logger_devnull]
level = DEBUG
qualname = devnull
handlers = devnull
formatter = simpleFormatter
propagate = 0

[handler_devnull]
class = logging.handlers.WatchedFileHandler
level = DEBUG
formatter = simpleFormatter
args = ('/dev/null',)

[logger_root]
level = DEBUG
handlers = root
qualname = root
formatter = simpleFormatter
propagate = 0

[handler_root]
class = logging.handlers.WatchedFileHandler
level = DEBUG
formatter = simpleFormatter
args = ('/dev/null',)

[logger_agent-default]
level = INFO
qualname = agent-default
handlers = agent-default
formatter = simpleFormatter
propagate = 0

[handler_agent-default]
class = logging.handlers.WatchedFileHandler
level = INFO
formatter = simpleFormatter
args = ('/var/log/amplify-agent/agent.log', 'a', None, 1)

Server:
Debian Bullseye 11.2
Nginx 1.20.2
MariaDB 10.5.12

**Comment by defanator** [comment]
@howdu could you please turn on debug-level logging in agent, restart it, and post full traceback for that TypeError exception here? (it should appear in log)

https://amplify.nginx.com/docs/guide-installing-and-managing-nginx-amplify-agent.html#agent-logfile

**Comment by howdu** [comment]
Thanks I was sure I had already done that but it did the trick and gave me more info. 

But still no mysql I found this related issue but it doesn't look to have been resolved since 2020. 
https://github.com/nginxinc/nginx-amplify-agent/issues/191
supervisor failed to find running mysqld via "ps xao pid,ppid,command | grep -E 'mysqld( |$)'" due to AmplifySubprocessError
supervisor additional info:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/amplify/ext/mysql/managers.py", line 154, in _find_local
    ps, _ = (ps, None) if ps is not None else subp.call(PS_CMD)
  File "/usr/lib/python3/dist-packages/amplify/agent/common/util/subp.py", line 33, in call
    raise AmplifySubprocessError(message=command, payload=dict(returncode=process.returncode, error=raw_err))
amplify.agent.common.errors.AmplifySubprocessError: (message=ps xao pid,ppid,command | grep -E 'mysqld( |$)', payload={'returncode': 1, 'error': ''})

If I run without the pipe
ps xao pid,ppid,command

I don't get mysql only mariadbd 
846097       1 /usr/sbin/mariadbd

AlsoI had to delete the default fpm config
2022-01-19 15:19:02,899 [884853] supervisor found a pool "www" with missing or commented directives "status_path" {'name': 'www', 'file': '/etc/php/7.3/fpm/pool.d/www.conf', 'listen': '/run/php/php7.3-fpm.sock', 'status_path': None}
2022-01-19 15:19:02,900 [884853] supervisor found a pool "www" with missing or commented directives "status_path" {'name': 'www', 'file': '/etc/php/8.1/fpm/pool.d/www.conf', 'listen': '/run/php/php8.1-fpm.sock', 'status_path': None}
2022-01-19 15:19:02,900 [884853] supervisor found a pool "www" with missing or commented directives "status_path" {'name': 'www', 'file': '/etc/php/8.0/fpm/pool.d/www.conf', 'listen': '/run/php/php8.0-fpm.sock', 'status_path': None}

**Comment by defanator** [comment]
@howdu let's not mix different issues in single report - from your initial description it seems like you've had problems with all metrics, not limited to mysql/mariadb. Were you able to get full traceback of TypeError exception so far?

**Comment by howdu** [comment]
No worries thought they might be related.

It takes a few minutes before this error is thrown: 
2022-01-19 16:14:54,473 [958014] bridge_manager modified payload; current payload stats: meta - 1, metrics - 1, events - 1, configs - 1
2022-01-19 16:14:54,474 [958014] bridge_manager http delay set to 4 (fails: 1)
2022-01-19 16:14:54,475 [958014] bridge_manager failed to push data due to TypeError
2022-01-19 16:14:54,475 [958014] bridge_manager additional info:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/amplify/agent/managers/bridge.py", line 119, in _send_payload
    context.http_client.post('update/', data=self.payload)
  File "/usr/lib/python3/dist-packages/amplify/agent/common/util/http.py", line 128, in post
    return self.make_request(url, 'post', data=data, timeout=timeout, json=json)
  File "/usr/lib/python3/dist-packages/amplify/agent/common/util/http.py", line 79, in make_request
    payload = ujson.encode(data) if data else '{}'
TypeError: <map object at 0x7f4da80d51f0> is not JSON serializable
2022-01-19 16:14:54,475 [958014] bridge_manager finished flush_all; new payload stats: meta - 1, metrics - 1, events - 1, configs - 1

Full log here:
https://www.dropbox.com/s/9arb54h91cz3zz7/agent.log?dl=0

**Comment by defanator** [comment]
@howdu thanks for sharing the log. Could you please show your php-fpm configs? You can reach out to me via maintainer's contact (use `dpkg -s nginx-amplify-agent | grep "^Maintainer"` to get it). Apologies - we're currently trying to figure out how to restore normal support channel for Amplify users.

**Comment by lacosteque** [comment]
> Setting up a new server but amplify appears to randomly stop reporting.
> 
> Looking at my log bridge_manager appears to work and then stop working.
> 
> Also mysql is not appearing even though the extension is enabled, mysql user created and verified the password is correct viewing the global stats.

For the agent to see the base metrics, you need to make changes.
Either change the bin file in the system or make changes in the agent itself.
The agent tries to find the process by the file mysqld, and you probably he mariadbd, also include in the configuration of the agent 
```
[mysql] 
remote = True
```


At least it worked for me after these changes. And about bridge_manager, I noticed that if nginx uses at least one host with https, agent does not collect metrics. 

I think there is a problem with the latest version of the agent, on other servers version 1.7 works and it does not bother https protocols. But 1.8 already suffers, apparently something with Python3 not befriended.

**Comment by inspired-geek** [comment]
> No worries thought they might be related.
> 
> It takes a few minutes before this error is thrown: 2022-01-19 16:14:54,473 [958014] bridge_manager modified payload; current payload stats: meta - 1, metrics - 1, events - 1, configs - 1 2022-01-19 16:14:54,474 [958014] bridge_manager http delay set to 4 (fails: 1) 2022-01-19 16:14:54,475 [958014] bridge_manager failed to push data due to TypeError 2022-01-19 16:14:54,475 [958014] bridge_manager additional info: Traceback (most recent call last): File "/usr/lib/python3/dist-packages/amplify/agent/managers/bridge.py", line 119, in _send_payload context.http_client.post('update/', data=self.payload) File "/usr/lib/python3/dist-packages/amplify/agent/common/util/http.py", line 128, in post return self.make_request(url, 'post', data=data, timeout=timeout, json=json) File "/usr/lib/python3/dist-packages/amplify/agent/common/util/http.py", line 79, in make_request payload = ujson.encode(data) if data else '{}' TypeError: <map object at 0x7f4da80d51f0> is not JSON serializable 2022-01-19 16:14:54,475 [958014] bridge_manager finished flush_all; new payload stats: meta - 1, metrics - 1, events - 1, configs - 1
> 
> Full log here: https://www.dropbox.com/s/9arb54h91cz3zz7/agent.log?dl=0

I have the same problem with freshly installed agent on rhel8 system. Have you found resolution yet?

**Comment by lacosteque** [comment]
> 

Hi
Turn off SSL verification in agent and everything will work fine.

1) Try to do it in the agent's personal cabinet
2) If it does not help, comment out the line in the script itself

**Comment by inspired-geek** [comment]
Thanks, it does help!
But what about SSL verification? It just doesn't work in recent version of the agent?

**Comment by lacosteque** [comment]
> Thanks, it does help! But what about SSL verification? It just doesn't work in recent version of the agent?

I do not know, it is better to ask the developers. For example on Debian, I had this error at first, then it fixed itself and the agent started sending metrics again. With rhle8 this did not happen and I found a way to solve it by using SSL)

**Comment by nkashiv** [comment]
@howdu @inspired-geek This looks like the same issue at #218 
Please can you try this solution https://github.com/nginxinc/nginx-amplify-agent/issues/218#issuecomment-1054506243 and see if it works for you.

**Comment by nkashiv** [comment]
The latest [update](https://github.com/nginxinc/nginx-amplify-agent/pull/223) fixed this issue. Please update your agent to get it.

**Comment by howdu** [comment]
> The latest [update](https://github.com/nginxinc/nginx-amplify-agent/pull/223) fixed this issue. Please update your agent to get it.

Confirmed thanks - it's been working well for the past 12 hours without crashing.
