### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by Ferrisbane** [nginxinc/nginx-amplify-agent#34]
Hello, I installed amplify using the manual install documentation, as I use the Raspberry Pi as a dev server and would like to monitor it via nginx amplify.

I have tried to see if I can find/fix the issue below with no luck.

```
supervisor run failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.39-py2.7.egg/amplify/agent/managers/abstract.py", line 128, in _run
    self._discover()
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.39-py2.7.egg/amplify/agent/managers/abstract.py", line 103, in _discover
    self._discover_objects()
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.39-py2.7.egg/amplify/agent/managers/system.py", line 34, in _discover_objects
    sys_object = SYSTEM_OBJECT_MAP[data['type']](data=data)
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.39-py2.7.egg/amplify/agent/objects/system/object.py", line 30, in __init__
    self._setup_meta_collector()
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.39-py2.7.egg/amplify/agent/objects/system/object.py", line 38, in _setup_meta_collector
    collector_cls = self._import_collector_class('system', 'meta')
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.39-py2.7.egg/amplify/agent/objects/abstract.py", line 148, in _import_collector_class
    cls = loader.import_class(class_path)
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.39-py2.7.egg/amplify/agent/common/util/loader.py", line 16, in import_class
    return getattr(module, class_name)
AttributeError: 'module' object has no attribute 'RaspbianSystemMetaCollector'
```

**Comment by dedm** [comment]
Thanks for the report! We will fix that issue soon.

**Comment by Ferrisbane** [comment]
Nice! thanks :)

**Comment by Ferrisbane** [comment]
Is there any news on this? I can help test if needed.

thanks.

**Comment by dedm** [comment]
Oh, sorry, @Ferrisbane. You can try the latest version of the agent (0.41) and it should work.
Let us know !

**Comment by Ferrisbane** [comment]
Thanks, I have updated to 0.41.

I am now getting this error (below) however I am unsure if this is related to the pi or an issue with my nginx setup.

I am going try and debug later on.
But the pi server is now showing data on the site :)
Thanks

```
2017-01-12 22:15:59,427 [14922] supervisor run failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.41-py2.7.egg/amplify/agent/managers/abstract.py", line 135, in _run
    self._discover()
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.41-py2.7.egg/amplify/agent/managers/abstract.py", line 110, in _discover
    self._discover_objects()
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.41-py2.7.egg/amplify/agent/managers/nginx.py", line 64, in _discover_objects
    new_obj = self._init_nginx_object(data=data)
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.41-py2.7.egg/amplify/agent/managers/nginx.py", line 44, in _init_nginx_object
    return NginxObject(data=data)
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.41-py2.7.egg/amplify/agent/objects/nginx/object.py", line 80, in __init__
    self._setup_error_logs()
  File "/usr/local/lib/python2.7/dist-packages/nginx_amplify_agent-0.41-py2.7.egg/amplify/agent/objects/nginx/object.py", line 259, in _setup_error_logs
    log_level = log_data['log_level']
KeyError: 'log_level'
```

**Comment by dedm** [comment]
Looks like a problem with parsing. Would you mind to send me your config so we could work on it?

**Comment by Ferrisbane** [comment]
https://gist.github.com/Ferrisbane/fb1d895f6574eff88a3b2997c4abf878

I have edited the api key and uuid, but they are the same length etc.

**Comment by dedm** [comment]
Oh, I'm sorry. I meant your Nginx's config, not the agent config.

**Comment by Ferrisbane** [comment]
Oh :) I believe it's this file that is causing it:

`2017-01-14 22:00:45,096 [18817] supervisor failed to parse /etc/nginx/domains.conf due to ParseException`

This file just contains a list of domains, on my Pi it's just this line:
`server_name ~^(?<subdomain>.*)\.(?<domain>example\.net)$;`

Do you need the main config file aswell?

**Comment by dedm** [comment]
@Ferrisbane finally we found a bug and fixed it (https://github.com/nginxinc/nginx-amplify-agent/commit/cec71cba60dc679afb893a3fa79bb3f55bbb8697)! So please try to install the latest version (0.41-2) and let us know.

**Comment by Ferrisbane** [comment]
Yes the update has fixed the error.
I have updated all my servers and the error has gone from all.

Thanks for the help.
