### ISSUE TITLE
"supervisor  failed to find bin_path, prefix and conf_path"

### ISSUE THREAD

**Issue by jahed** [nginxinc/nginx-amplify-agent#41]
Since moving over to OpenResty, I've been getting this error being logged constantly. I'm also not getting any nginx metrics coming through.

```
2016-12-08 23:01:48,663 [22648] supervisor failed to find bin_path, prefix and conf_path for nginx: master process /usr/local/openresty/nginx/sbin/nginx -p /etc/www -c /etc/www/nginx/nginx.conf
```

Not sure why this is happening. Looking at the code, there seems to be a problem with parsing the command but the logic seems sane to me.

```
Name        : nginx-amplify-agent
Arch        : i386
Version     : 0.40
Release     : 2.el6
Size        : 18 M
Repo        : installed
From repo   : nginx-amplify
Summary     : NGINX Amplify Agent
URL         : https://github.com/nginxinc
License     : 2-clause BSD-like license
Description : The NGINX Amplify Agent is a small, Python application that
            : provides system and NGINX metric collection. It is part of
            : NGINX Amplify - the monitoring and configuration assistance
            : service for NGINX.
            : This package installs and runs NGINX Amplify Agent daemon.
            : See http://nginx.com/amplify for more information
```

**Comment by gshulegaard** [comment]
Hi @jahed ,

Thanks for the report, we don't officially support OpenResty at this time, but could you post the output of the following: `ps xao pid,ppid,command | grep 'nginx[:]'`?

Best,

Grant

**Comment by jahed** [comment]
OpenResty is pretty much just a convenient way of getting nginx pre-built with some useful modules. Don't see why it wouldn't work.

```
22885     1 nginx: master process /usr/local/openresty/nginx/sbin/nginx -p /etc/www -c /etc/www/nginx/nginx.conf
26028 22885 nginx: worker process                                                         
26029 22885 nginx: cache manager process     
```

**Comment by gshulegaard** [comment]
Hi @jahed ,

Could you post the output of: `/usr/local/openresty/nginx/sbin/nginx -V`?  But please make sure to run it as the same user that runs your `amplify-agent`.

Thanks in advance!

Grant

**Comment by gshulegaard** [comment]
Hi @jahed ,

May I ask you to download and run the following script and send me its output via email?
https://raw.githubusercontent.com/nginxinc/nginx-amplify-agent/master/packages/collect-env.sh

Also, if you could enable DEBUG logging and send me your `/var/log/amplify-agent/agent.log` after some of the original reported errors, it will help us diagnose the issue.

Thanks in advance!

Grant

**Comment by jahed** [comment]
Thanks for the debug log tip, I've found the issue. It's this line:

https://github.com/nginxinc/nginx-amplify-agent/blob/master/amplify/agent/objects/nginx/binary.py#L48

Here's the result of running:

```
/usr/local/openresty/nginx/sbin/nginx -V

nginx version: openresty/1.11.2.2
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 
built with OpenSSL 1.0.2j  26 Sep 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include' --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.60 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.31 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.06 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.7 --add-module=../ngx_lua_upstream-0.06 --add-module=../headers-more-nginx-module-0.32 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.17 --add-module=../redis2-nginx-module-0.13 --add-module=../redis-nginx-module-0.3.7 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib' --with-pcre-jit --with-ipv6 --with-stream --with-stream_ssl_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-file-aio --with-dtrace-probes --with-http_ssl_module
```

The `configure arguments` values have `:`  in them, for example:

```
--with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib'
```

which can't be unpacked, as seen in the debug logs.

```
2016-12-09 00:58:00,227 [28687] supervisor 
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/amplify/agent/managers/nginx.py", line 241, in _find_all
    bin_path, prefix, conf_path, version = get_prefix_and_conf_path(cmd)
  File "/usr/lib/python2.6/site-packages/amplify/agent/objects/nginx/binary.py", line 94, in get_prefix_and_conf_path
    parsed_v = nginx_v(bin_path)
  File "/usr/lib/python2.6/site-packages/amplify/agent/objects/nginx/binary.py", line 48, in nginx_v
    key, value = parts
ValueError: too many values to unpack
2016-12-09 00:58:00,227 [28687] supervisor nginx objects: []
2016-12-09 00:58:00,228 [28687] supervisor plus objects: []
```

So I guess the fix is to split only on the first `:` rather than the entire line. I'd send a pull request but my Python is very rusty and it'll probably take me a while.

**Comment by gshulegaard** [comment]
@jahed Thanks for looking into the debug logs.  If you could still send me the `collect-env.sh` output and some debug logs when it is convenient I'll attach it to the internal ticket so we can investigate it in our environments time permitting.

**Comment by dedm** [comment]
Should be fixed in https://github.com/nginxinc/nginx-amplify-agent/commit/1def4d20e2c79031b2042a15a3aadfb6e347a190

Please try to install the latest agent (0.41)
