### ISSUE TITLE
AttributeError in metrics.py 44

### ISSUE THREAD

**Issue by lewnie** [nginxinc/nginx-amplify-agent#47]
_setup_status_page raises an AttributeError: 'str' object has no attribute 'contains'.

I'm running fpm on 127.0.0.1:9000, perhaps "':' in listen:" could work?

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/agent/managers/abstract.py", line 134, in _run
    self._discover()
  File "/usr/lib/python2.7/dist-packages/amplify/agent/managers/abstract.py", line 109, in _discover
    self._discover_objects()
  File "/usr/lib/python2.7/dist-packages/amplify/ext/phpfpm/managers/pool.py", line 50, in _discover_objects
    new_obj = PHPFPMPoolObject(data=data)
  File "/usr/lib/python2.7/dist-packages/amplify/ext/phpfpm/objects/pool.py", line 44, in __init__
    self._setup_metrics_collector()
  File "/usr/lib/python2.7/dist-packages/amplify/ext/phpfpm/objects/pool.py", line 92, in _setup_metrics_collector
    PHPFPMPoolMetricsCollector(object=self, interval=self.intervals['metrics'])
  File "/usr/lib/python2.7/dist-packages/amplify/ext/phpfpm/collectors/pool/metrics.py", line 30, in __init__
    self.status_page = self._setup_status_page()
  File "/usr/lib/python2.7/dist-packages/amplify/ext/phpfpm/collectors/pool/metrics.py", line 44, in _setup_status_page
    elif listen.contains(':'):
AttributeError: 'str' object has no attribute 'contains'

**Comment by dedm** [comment]
@lewnie thanks for the bug!

May I ask you to share some info about your system? Version of python, OS name and php-fpm config will be helpful! 

Thanks in advance

**Comment by dedm** [comment]
@lewnie right now you can manually fix the 44th line in `/usr/lib/python2.7/dist-packages/amplify/ext/phpfpm/collectors/pool/metrics.py`: put `elif ':' in listen:` instead of `elif listen.contains(':'):` 

this is a stupid bug and we will fix in the next release

**Comment by lewnie** [comment]
Hi dedm,

quiet a response time... Thank's for that.

I'm running php 7.1.3, Python 2.7 on Debian 8.7(jessie) and my fpm config looks like that:

[www]
user = www-data
group = www-data
listen = 127.0.0.1:9070
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.status_path = /status

Just as info aside, changing "listen.contains(':'):" to "':' in listen:" did the trick for now.
Thank's again for your quick response.

**Comment by dedm** [comment]
Closed in https://github.com/nginxinc/nginx-amplify-agent/commit/709eaf18290ecd1e11354551a28b405930b3a14d
