### ISSUE TITLE
bridge_manager failed to push data due to ConnectTimeout

### ISSUE THREAD

**Issue by becksgrohl** [nginxinc/nginx-amplify-agent#50]
i've get errors in my agent.log : 

2017-04-30 10:50:44,669 [27352] bridge_manager failed POST "https://receiver.amplify.nginx.com:443/1.3/b13fa7ecc48f621babe245332478c7f8/update/", exception: "HTTPSConnec
tionPool(host='receiver.amplify.nginx.com', port=443): Max retries exceeded with url: /1.3/b13fa7ecc48f621babe245332478c7f8/update/ (Caused by ConnectTimeoutError(<reque
sts.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x14ef1d0>, 'Connection to receiver.amplify.nginx.com timed out. (connect timeout=5.0)'))"
2017-04-30 10:50:44,670 [27352] bridge_manager [None] post https://receiver.amplify.nginx.com:443/1.3/b13fa7ecc48f621babe245332478c7f8/update/ 500 2555 0 5.044
2017-04-30 10:50:44,670 [27352] bridge_manager failed to push data due to ConnectTimeout
2017-04-30 10:51:04,839 [27352] supervisor failed POST "https://receiver.amplify.nginx.com:443/1.3/b13fa7ecc48f621babe245332478c7f8/agent/", exception: "HTTPSConnectionP
ool(host='receiver.amplify.nginx.com', port=443): Max retries exceeded with url: /1.3/b13fa7ecc48f621babe245332478c7f8/agent/ (Caused by ConnectTimeoutError(<requests.pa
ckages.urllib3.connection.VerifiedHTTPSConnection object at 0x14ef250>, 'Connection to receiver.amplify.nginx.com timed out. (connect timeout=5.0)'))"
2017-04-30 10:51:04,840 [27352] supervisor [None] post https://receiver.amplify.nginx.com:443/1.3/b13fa7ecc48f621babe245332478c7f8/agent/ 500 90 0 5.006
2017-04-30 10:51:04,840 [27352] supervisor could not connect to cloud
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/amplify/agent/supervisor.py", line 241, in talk_to_cloud
    context.http_client.post('agent/', data=root_object)
  File "/usr/lib/python2.7/site-packages/amplify/agent/common/util/http.py", line 130, in post
    return self.make_request(url, 'post', data=data, timeout=timeout, json=json)
  File "/usr/lib/python2.7/site-packages/amplify/agent/common/util/http.py", line 112, in make_request
    raise e
ConnectTimeout: HTTPSConnectionPool(host='receiver.amplify.nginx.com', port=443): Max retries exceeded with url: /1.3/b13fa7ecc48f621babe245332478c7f8/agent/ (Caused by 
ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x14ef250>, 'Connection to receiver.amplify.nginx.com timed out. (connect tim
eout=5.0)'))
2017-04-30 10:52:49,997 [27352] bridge_manager failed POST "https://receiver.amplify.nginx.com:443/1.3/b13fa7ecc48f621babe245332478c7f8/update/", exception: "HTTPSConnec
tionPool(host='receiver.amplify.nginx.com', port=443): Max retries exceeded with url: /1.3/b13fa7ecc48f621babe245332478c7f8/update/ (Caused by ConnectTimeoutError(<reque
sts.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1861790>, 'Connection to receiver.amplify.nginx.com timed out. (connect timeout=5.0)'))"
2017-04-30 10:52:49,997 [27352] bridge_manager [None] post https://receiver.amplify.nginx.com:443/1.3/b13fa7ecc48f621babe245332478c7f8/update/ 500 3842 0 5.292
2017-04-30 10:52:49,997 [27352] bridge_manager failed to push data due to ConnectTimeout
2017-04-30 10:53:10,164 [27352] supervisor failed POST "https://receiver.amplify.nginx.com:443/1.3/b13fa7ecc48f621babe245332478c7f8/agent/", exception: "HTTPSConnectionP
ool(host='receiver.amplify.nginx.com', port=443): Max retries exceeded with url: /1.3/b13fa7ecc48f621babe245332478c7f8/agent/ (Caused by ConnectTimeoutError(<requests.pa
ckages.urllib3.connection.VerifiedHTTPSConnection object at 0x186a690>, 'Connection to receiver.amplify.nginx.com timed out. (connect timeout=5.0)'))"
2017-04-30 10:53:10,164 [27352] supervisor [None] post https://receiver.amplify.nginx.com:443/1.3/b13fa7ecc48f621babe245332478c7f8/agent/ 500 90 0 5.007
2017-04-30 10:53:10,164 [27352] supervisor could not connect to cloud
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/amplify/agent/supervisor.py", line 241, in talk_to_cloud
    context.http_client.post('agent/', data=root_object)
  File "/usr/lib/python2.7/site-packages/amplify/agent/common/util/http.py", line 130, in post
    return self.make_request(url, 'post', data=data, timeout=timeout, json=json)
  File "/usr/lib/python2.7/site-packages/amplify/agent/common/util/http.py", line 112, in make_request
    raise e
ConnectTimeout: HTTPSConnectionPool(host='receiver.amplify.nginx.com', port=443): Max retries exceeded with url: /1.3/b13fa7ecc48f621babe245332478c7f8/agent/ (Caused by 
ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x186a690>, 'Connection to receiver.amplify.nginx.com timed out. (connect tim
eout=5.0)'))

and in my dashboard, An alert appears stating the system is not updating for at least 5-10 mnt then normal again. 

could you please inform what kind error/bugs is this ?

thanks for your attention and coorperation

**Comment by dedm** [comment]
@becksgrohl it looks like your system had problems with connectivity and Amplify agent couldn't reach our cloud. Do you have the same problems right now?

**Comment by becksgrohl** [comment]
@dedm thx for the respond, currently it's fine .. buat it so wierd if you said my cloud couldn't reach your cloud coz others cloud not have those error

**Comment by ptreyes** [comment]
Hey, this is actually quite interesting. We sometimes have reports like this when there's no connectivity from someone else's cloud to "our cloud" (which is in fact AWS us-west :)

Sometimes there are indeed connectivity issues with the AWS infrastructure and the rest of the world (or maybe, vice versa).

Would you mind keeping an eye on it, and if the same kind of problem appears again, then do some additional discovery? E.g.,

  - traceroute receiver.amplify.nginx.com
  - write down the exact time when there wasn't connectivity (or there was other issue), send such details over to us
  - check the graphs and see if anything was wrong with cpu/network/etc. right prior to the "outage"
  - check /var/log/amplify-agent/agent.log (maybe even turn the debug level for it, restart the agent, check the log)

Hope this helps

**Comment by tkriviradev** [comment]
Hello,

I have exactly the same issues it happen after debian 10 > 11 upgrade

# #2022-03-28 12:24:54,721 [9328] nginx_metrics [None] get http://127.0.0.1:80/nginx_status 200 10 106 0.004
2022-03-28 12:24:54,721 [9328] nginx_metrics 34d39fc314628b9ff20bfb12138a4c0cb407d6395fa5512cef844b95d9467663 collect in 0.006
2022-03-28 12:24:54,831 [9328] nginx_meta 34d39fc314628b9ff20bfb12138a4c0cb407d6395fa5512cef844b95d9467663 collect in 0.075
2022-03-28 12:24:55,016 [9328] supervisor system objects: ['e5389f19c285e6b27ce9f3cb150d4a97bad0ab4fa472deff1a5cc5c7194c6ae7']
2022-03-28 12:24:55,033 [9328] supervisor ps nginx output: ['   7533       1 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf', '   7534    7533 nginx: worker process', '   7535    7533 nginx: worker process', '   7536    7533 nginx: cache manager process', '']
2022-03-28 12:24:55,043 [9328] supervisor nginx objects: ['34d39fc314628b9ff20bfb12138a4c0cb407d6395fa5512cef844b95d9467663']
2022-03-28 12:24:55,044 [9328] supervisor status objects: []
2022-03-28 12:24:55,044 [9328] supervisor api objects: []
2022-03-28 12:24:55,674 [9328] bridge_manager failed POST "https://receiver.amplify.nginx.com:443/1.4/5147cd2d2fd569c76dbe47a18e2de225/update/", exception: "HTTPSConnectionPool(host='receiver.amplify.nginx.com', port=443): Read timed out. (read timeout=7.0)"
2022-03-28 12:24:55,675 [9328] bridge_manager 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/gevent/_ssl3.py", line 114, in wrap_socket
    return self.sslsocket_class(
  File "/usr/lib/python3/dist-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/usr/lib/python3/dist-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/usr/lib/python3/dist-packages/gevent/_ssl3.py", line 672, in do_handshake
    self._wait(self._read_event, timeout_exc=_SSLErrorHandshakeTimeout)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 151, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
socket.timeout: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 385, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='receiver.amplify.nginx.com', port=443): Read timed out. (read timeout=7.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/amplify/agent/common/util/http.py", line 94, in make_request
    r = self.session.post(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='receiver.amplify.nginx.com', port=443): Read timed out. (read timeout=7.0)
2022-03-28 12:24:55,765 [9328] bridge_manager 
2022-03-28 12:24:55,766 [9328] bridge_manager [None] post https://receiver.amplify.nginx.com:443/1.4/5147cd2d2fd569c76dbe47a18e2de225/update/ 500 1447 0 7.809
2022-03-28 12:24:55,766 [9328] bridge_manager http delay set to 10 (fails: 1)
2022-03-28 12:24:55,766 [9328] bridge_manager failed to push data due to ReadTimeout
2022-03-28 12:24:55,766 [9328] bridge_manager additional info:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/gevent/_ssl3.py", line 114, in wrap_socket
    return self.sslsocket_class(
  File "/usr/lib/python3/dist-packages/gevent/_ssl3.py", line 312, in __init__
    raise x
  File "/usr/lib/python3/dist-packages/gevent/_ssl3.py", line 308, in __init__
    self.do_handshake()
  File "/usr/lib/python3/dist-packages/gevent/_ssl3.py", line 672, in do_handshake
    self._wait(self._read_event, timeout_exc=_SSLErrorHandshakeTimeout)
  File "src/gevent/_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src/gevent/_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src/gevent/_waiter.py", line 151, in gevent._gevent_c_waiter.Waiter.get
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
socket.timeout: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 385, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='receiver.amplify.nginx.com', port=443): Read timed out. (read timeout=7.0)
