### ISSUE TITLE
phpfpm_meta failed to find php-fpm bin path

### ISSUE THREAD

**Issue by gemal** [nginxinc/nginx-amplify-agent#55]
`2017-06-16 12:54:34,113 [16468] phpfpm_meta failed to find php-fpm bin path, last attempt: "ls -la /proc/19601/exe" failed due to AmplifySubprocessError`

```
# ls -la /proc/19601/exe
lrwxrwxrwx 1 apache apache 0 Jun 16 12:46 /proc/19601/exe -> /usr/sbin/php-fpm-7.0
# dir /usr/sbin/php-fpm-7.0 
-rwxr-xr-x 1 root root 4270976 Mar  6 19:50 /usr/sbin/php-fpm-7.0
```

**Comment by gemal** [comment]
after enabling the status_path in php-fpm I get:

```
2017-06-16 13:19:14,013 [20995] phpfpm_pool_metrics dda4c7c9790db945e0c3ab0d3c0691921b7252665486335e06d3da4923c44b61 collector run failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/agent/collectors/abstract.py", line 66, in run
    self._collect()
  File "/usr/lib/python2.7/dist-packages/amplify/agent/collectors/abstract.py", line 96, in _collect
    self.collect()
  File "/usr/lib/python2.7/dist-packages/amplify/ext/phpfpm/collectors/pool/metrics.py", line 72, in collect
    self._current = self._parse_status_page(self.status_page.get_status())
  File "/usr/lib/python2.7/dist-packages/amplify/ext/phpfpm/util/fpmstatus.py", line 133, in get_status
    context.log.error('failed to communicate with pool at "%s"' % self.connection)
TypeError: not all arguments converted during string formatting

```

**Comment by gemal** [comment]
```
2017-06-16 13:33:31,346 [23059] phpfpm_meta failed to find php-fpm bin path, last attempt: "ls -la /proc/20891/exe" failed due to AmplifySubprocessError
2017-06-16 13:33:31,346 [23059] phpfpm_meta additional info:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/ext/phpfpm/collectors/master/meta.py", line 80, in bin_path
    ls, _ = subp.call(ls_cmd)
  File "/usr/lib/python2.7/dist-packages/amplify/agent/common/util/subp.py", line 33, in call
    raise AmplifySubprocessError(message=command, payload=dict(returncode=process.returncode))
AmplifySubprocessError: (message=ls -la /proc/20891/exe, payload={'returncode': 2})
2017-06-16 13:33:31,346 [23059] phpfpm_meta 635db7e5f5eab18cf07e72c2391ce39436f68cd6706c7b07e7e37d936d78fe9e collect in 0.021
2017-06-16 13:33:31,347 [23059] phpfpm_metrics 635db7e5f5eab18cf07e72c2391ce39436f68cd6706c7b07e7e37d936d78fe9e collect in 0.000
2017-06-16 13:33:31,472 [23059] supervisor system objects: ['a4c65bea82428d157e3d760269e780e861636763302a04894071135ef357479f']
2017-06-16 13:33:31,480 [23059] supervisor ps nginx output: ['21669     1 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf', '21671 21669 nginx: worker process                   ', '']
2017-06-16 13:33:31,485 [23059] supervisor nginx objects: ['7032a5d4b2a3aab46fb91297f75bee5f84000237e65f128fa6e9eddc53021a88']
2017-06-16 13:33:31,485 [23059] supervisor plus objects: []
2017-06-16 13:33:31,485 [23059] supervisor phpfpm_pool objects: ['dda4c7c9790db945e0c3ab0d3c0691921b7252665486335e06d3da4923c44b61']
2017-06-16 13:33:31,492 [23059] supervisor ps php-fpm output: ['20885     1 php-fpm: master process (/etc/php-fpm.conf)', '20887 20885 php-fpm: pool www                ', '20888 20885 php-fpm: pool www                ', '20889 20885 php-fpm: pool www                ', '20890 20885 php-fpm: pool www                ', '20891 20885 php-fpm: pool www                ', '']
2017-06-16 13:33:31,492 [23059] supervisor phpfpm objects: ['635db7e5f5eab18cf07e72c2391ce39436f68cd6706c7b07e7e37d936d78fe9e']

```

**Comment by ptreyes** [comment]
So, the "ls" error should not affect anything but detecting the php-fpm version. Given the fact, there could be many concurrent php-fpm master/worker instances running on the same host, we don't have many means to reliably detect what versions are there. We try to do that via checking /proc and seeing if we can deduct the path to the running php-fpm binary, and then calling it with "-v". This fails if the agent's eUID is not that of the running php-fpm binary.

See more here:
https://github.com/nginxinc/nginx-amplify-doc/blob/master/amplify-guide.md#php-fpm-metrics

The other issue with "failed to communicate with pool" - do you use the latest agent version 0.44?

**Comment by ptreyes** [comment]
Can you please address this via Intercom? It would be good if you could attach the debug agent log with the "string formatting" issue. Many thanks!

**Comment by dedm** [comment]
Should be fixed in https://github.com/nginxinc/nginx-amplify-agent/commit/386e81e37011a5753eb6fae7a30586bcfaa93118

@gemal  please update the agent (latest version is 0.44-2) and let us know if you still have this bug

**Comment by gemal** [comment]
after update to latest release I see:

```
017-06-19 12:15:54,685 [24174] MainThread configtest check
2017-06-19 12:15:55,265 [24174] MainThread [615a45a53d6f6cbe9bd9b712b829c1ce] post https://receiver.amplify.nginx.com:443/1.3/057cd782435cfcc098663fd878f20398/agent/ 200 10 4 0.579
2017-06-19 12:15:55,924 [24192] supervisor [4adef225e01b80ef64c9a7cef0e7cdcb] post https://receiver.amplify.nginx.com:443/1.3/057cd782435cfcc098663fd878f20398/agent/ 200 90 4 0.614
2017-06-19 12:16:00,993 [24192] supervisor agent started, version=0.44-2 pid=24192 uuid=786f4cdc01e25b629fb1b97ae23d5390 hostname=i-007e2c18c674e962b
2017-06-19 12:16:04,895 [24192] supervisor ssl certificate found xxxx.crt
2017-06-19 12:16:05,045 [24192] phpfpm_meta failed to find php-fpm bin path, last attempt: "ls -la /proc/24088/exe" failed due to AmplifySubprocessError
2017-06-19 12:16:15,068 [24192] phpfpm_meta failed to find php-fpm bin path, last attempt: "ls -la /proc/24088/exe" failed due to AmplifySubprocessError
2017-06-19 12:16:25,090 [24192] phpfpm_meta failed to find php-fpm bin path, last attempt: "ls -la /proc/24088/exe" failed due to AmplifySubprocessError
2017-06-19 12:16:35,112 [24192] phpfpm_meta failed to find php-fpm bin path, last attempt: "ls -la /proc/24088/exe" failed due to AmplifySubprocessError
2017-06-19 12:16:45,135 [24192] phpfpm_meta failed to find php-fpm bin path, last attempt: "ls -la /proc/24088/exe" failed due to AmplifySubprocessError
2017-06-19 12:16:55,158 [24192] phpfpm_meta failed to find php-fpm bin path, last attempt: "ls -la /proc/24088/exe" failed due to AmplifySubprocessError
2017-06-19 12:16:56,496 [24192] bridge_manager [82edafc55fbed7508f07427bb69d38e2] post https://receiver.amplify.nginx.com:443/1.3/057cd782435cfcc098663fd878f20398/update/ 202 1880 0 0.541
```


```
[ec2-user]# ls -la /proc/24088/exe
lrwxrwxrwx 1 apache apache 0 Jun 19 12:15 /proc/24088/exe -> /usr/sbin/php-fpm-7.0
```

**Comment by ptreyes** [comment]
Ok, please wait and see if you're getting php-fpm metrics.

The "ls" problem is the agent trying to detect the version of the php-fpm and failing because you run php-fpm as apache, and the agent as a different eUID. That's not critical - you'll be just missing the php version information in the UI.
