### ISSUE TITLE
Location regex parsing error

### ISSUE THREAD

**Issue by zahariash** [nginxinc/nginx-amplify-agent#64]
Hi,

Version 0.45-1 have some problem with "=" in location regex. Escaping with backslash doesn't help.

```
    # ParseSyntaxException
    location ~ ^(/page/[0-9]+/\?arg=) {
    }

    # ok
    location ~ ^(/page/[0-9]+/\?arg.) {
    }
```

Full error:
```
2017-08-11 11:45:52,300 [5985] supervisor failed to parse /etc/nginx/conf.d/xxx.conf due to ParseSyntaxException
2017-08-11 11:45:52,300 [5985] supervisor additional info:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/agent/objects/nginx/config/parser.py", line 463, in __pyparse
    parsed = list(self.script.parseString(source, parseAll=True))
  File "/usr/lib/python2.7/dist-packages/amplify/pyparsing.py", line 1632, in parseString
    raise exc
ParseSyntaxException: Expected "}" (at char 13510), (line:388, col:5)
```

**Comment by dedm** [comment]
@zahariash sorry about that bug, and thanks for the report! We will fix it soon.
