### ISSUE TITLE
Amazon Linux: nginx_alog failed

### ISSUE THREAD

**Issue by soukiii** [nginxinc/nginx-amplify-agent#7]
I have installed amplify on Centos with no problems. I can now (thans to closed #1) install on Amazon Linux too, but data collection is not working. Here is my log (key edited):

```
2015-11-16 22:46:35,581 [2110] MainThread post https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/agent/ 200 10 3 0.624
2015-11-16 22:46:36,423 [2132] supervisor post https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/agent/ 200 10 3 0.593
2015-11-16 22:53:21,979 [2132] supervisor post https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/agent/ 200 110 3 0.623
2015-11-16 22:53:21,998 [2132] nginx_metrics get http://127.0.0.1:80/nginx_stub_status 200 10 120 0.002
2015-11-16 23:00:24,690 [2132] nginx_config running /usr/sbin/nginx -t -c /etc/nginx/nginx.conf
2015-11-16 23:00:28,270 [2132] supervisor post https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/agent/ 200 110 3 0.689
2015-11-16 23:00:28,276 [2132] nginx_metrics get http://127.0.0.1:80/nginx_stub_status 200 10 120 0.003
2015-11-16 23:00:28,454 [2132] bridge post https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/meta/ 202 1310 0 0.177
2015-11-16 23:00:37,292 [2132] nginx_alog a909a2f58c40790fc3617f02083e96f7 failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/amplify/agent/containers/abstract.py", line 167, in run
    self._collect()
  File "/usr/lib/python2.7/site-packages/amplify/agent/containers/abstract.py", line 179, in _collect
    self.collect()
  File "/usr/lib/python2.7/site-packages/amplify/agent/containers/nginx/collectors/accesslog.py", line 38, in collect
    if parsed['malformed']:
KeyError: 'malformed'
2015-11-16 23:07:23,682 [2132] nginx_metrics get http://127.0.0.1:80/nginx_stub_status 200 10 120 0.002
2015-11-16 23:07:24,532 [2132] supervisor post https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/agent/ 200 110 3 0.802
2015-11-16 23:07:24,780 [2132] bridge post https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/meta/ 202 1310 0 0.167
2015-11-16 23:07:24,943 [2132] bridge post https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/metrics/ 202 1131 0 0.159
2015-11-16 23:07:25,102 [2132] bridge post https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/events/ 202 539 0 0.158
2015-11-16 23:07:30,667 [2132] bridge failed to post "https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/nginx/config/", exception: "413 Client Error: Request Entity Too Large for url: https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/nginx/config/"
2015-11-16 23:07:30,667 [2132] bridge post https://receiver.amplify.nginx.com:4443/1.0/9fdb566d***************************/nginx/config/ 413 1510806 0 0.459
2015-11-16 23:07:30,668 [2132] bridge failed to push data due to HTTPError

```

**Comment by dedm** [comment]
That's a bug. Thanks, we will fix it.

**Comment by gshulegaard** [comment]
@soukiii I have fixed the simple malformed key error, but could you send us the config file that you are trying to parse which is generating the HTTP 413 error?

Also, perhaps you could try and increase your POST limit.  At first glance, 1.5 MB of gzipped data should not be too large for our API.

Best,

**Comment by gshulegaard** [comment]
@soukiii Could we get 2-3 lines from your nginx access.log and the log definition format (from your config file).

If that's alright, you can send it to me directly at grant.hulegaard@nginx.com.

Best

**Comment by soukiii** [comment]
```
46.4.32.75 - [17/Nov/2015:00:20:49 +0100] GET https "/Stare-kolekce/CLASSIC-WOVEN-SHORT-LINED-2339"  200 0.113 14842  "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.5; http://www.majestic12.co.uk/bot.php?+)" club.sportmade.cz
85.25.210.234 - [17/Nov/2015:00:20:50 +0100] GET https "/robots.txt"  200 0.024 240  "-" "Mozilla/5.0 (compatible; worldwebheritage.org/1.1; +crawl@worldwebheritage.org)" www.nakupni-dum-praha.cz
88.198.15.40 - [17/Nov/2015:00:20:51 +0100] GET https "/cron/recommendation.php"  200 3.581 5  "-" "Mozilla/5.0 (Windows; U; Windows NT 5.1; rv:1.7.3) Gecko/20041001 Firefox/0.10.1" www.sportleader.cz

```

Log format:
```
log_format  mylog
'$remote_addr - [$time_local] $request_method $scheme "$request_uri"  '
        '$status $request_time $body_bytes_sent  "$http_referer" '
        '"$http_user_agent" $host';
```

**Comment by gshulegaard** [comment]
We fixed the key error and have written a test against your specific log format to verify our parser output...also an Ops engineer is tasked with looking into our API settings related to the HTTP error.

We will release a new version this week (with this fix).
