### ISSUE TITLE
running install-source.sh for FreeBSD 11.0 - Something failed:

### ISSUE THREAD

**Issue by tepung** [nginxinc/nginx-amplify-agent#71]
Downloaded install-source.sh and run it on my FreeBSD 11.0.
Finished running the script until  --- Finished successfully! ---

When tried to start it 

```
root@web:~ # sudo -u nginx python2.7 /usr/bin/nginx-amplify-agent.py start --config=/etc/amplify-agent/agent.conf --pid=/var/run/amplify-agent/amplify-agent.pid

Something failed:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nginx_amplify_agent-0.45-py2.7.egg/amplify/agent/common/util/configreader.py", line 60, in test
    pid_file=pid_file
  File "/usr/local/lib/python2.7/site-packages/nginx_amplify_agent-0.45-py2.7.egg/amplify/agent/common/context.py", line 91, in setup
    self._setup_http_client()
  File "/usr/local/lib/python2.7/site-packages/nginx_amplify_agent-0.45-py2.7.egg/amplify/agent/common/context.py", line 183, in _setup_http_client
    from amplify.agent.common.util.http import HTTPClient
  File "/usr/local/lib/python2.7/site-packages/nginx_amplify_agent-0.45-py2.7.egg/amplify/agent/common/util/http.py", line 4, in <module>
    import ujson
ImportError: /usr/local/lib/python2.7/site-packages/nginx_amplify_agent-0.45-py2.7.egg/amplify/ujson.so: Undefined symbol "strreverse"


root@web:~ # pkg info | grep python
python2-2_3                    The "meta-port" for version 2 of the Python interpreter
python27-2.7.12                Interpreted object-oriented programming language
root@web:~ #
root@web:~ # uname -a
FreeBSD xxxxx.xxx.xx 11.0-RELEASE-p12 FreeBSD 11.0-RELEASE-p12 #0: Wed Aug  9 10:03:39 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

```

Thanks for your effort on FreeBSD environment ...

**Comment by gshulegaard** [comment]
This seems to be a problem in one of our dependencies `ujson` specifically on FreeBSD.  We currently use version `1.33` of `ujson`.

Quick google search turned up this issue:

https://github.com/esnme/ultrajson/issues/180

It would appear that the forthcoming version of `ujson` no longer has this issue and some of the users in that ticket have had success installing from the `master` branch rather than the `1.35` and below release branches.  You could try this, although we cannot guarantee the new version will work flawlessly with our agent out of the box.

Since this isn't something we can fix (e.g. next version of `ujson` is not released yet), I am going to close this ticket for now...but once a new version of `ujson` is released that fixes this issue on FreeBSD please feel free to reopen it.

Thanks for the report!  I am sorry I cannot be of more help here.

**Comment by ptreyes** [comment]
Still checking :)

**Comment by tepung** [comment]
Thanks @gshulegaard, @ptreyes, hope to hear great news ..

**Comment by ptreyes** [comment]
Hi,

Thanks for waiting. Can you try the latest version of the script?
https://raw.githubusercontent.com/nginxinc/nginx-amplify-agent/master/packages/install-source.sh

Make sure to clean up the previously failed build, e.g. I had to do
sudo rm -rf /root/.cache
sudo rm -rf /root/.local
sudo rm -rf /usr/local/lib/python2.7/site-packages/nginx_amplify_agent-0.45-py2.7.egg
sudo rm -rf nginx-amplify-agent

**Comment by tepung** [comment]
Hi @ptreyes,

```
root@web:~ # sudo -u nginx python2.7 /usr/bin/nginx-amplify-agent.py start \
? --config=/etc/amplify-agent/agent.conf \
? --pid=/var/run/amplify-agent/amplify-agent.pid

Config file /etc/amplify-agent/agent.conf is OK

root@web:~ #

```

Amplify Agent able to run now with new script ..  and yes, now amplify showing graph ..
Thanks a lot for your big help .. now going to install to all my FreeBSD server.

I'll test on FreeBSD 10 and lower ..
Thanks again sir .. really appreciate it very much ...

**Comment by ptreyes** [comment]
Oh coo, nice :) Glad it worked for you! Closing this for now. Feel free to reach out through the Intercom chat in the UI as well.

**Comment by hiradyazdan** [comment]
@point-r I am having a similar issue on Alpine. Even though I have used the latest script as suggested and manually installed `ujson v1.35`, still getting the following errors:

```shell
Traceback (most recent call last):
	File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.4.0-py2.7.egg/amplify/agent/common/util/configreader.py", line 71, in test
	skip_uuid=True
	File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.4.0-py2.7.egg/amplify/agent/common/context.py", line 92, in setup
	self._setup_http_client()
	File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.4.0-py2.7.egg/amplify/agent/common/context.py", line 216, in _setup_http_client
	from amplify.agent.common.util.http import HTTPClient
	File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.4.0-py2.7.egg/amplify/gevent/builtins.py", line 93, in __import__
	result = _import(*args, **kwargs)
	File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.4.0-py2.7.egg/amplify/agent/common/util/http.py", line 4, in <module>
	import ujson
	File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.4.0-py2.7.egg/amplify/gevent/builtins.py", line 93, in __import__
	result = _import(*args, **kwargs)
	ImportError: Error relocating /usr/lib/python2.7/site-packages/nginx_amplify_agent-1.4.0-py2.7.egg/amplify/ujson.so: strreverse: symbol not found

```

Any ideas why?

**Comment by arpogo** [comment]
If you see ujson error:
`pip --no-cache-dir -q install git+git://github.com/esnme/ultrajson.git && \
      find / -path "*egg/amplify/ujson.so" -exec rm -rf {} \;`
