### ISSUE TITLE
Centos 7 + Directadmin fail to collect

### ISSUE THREAD

**Issue by Zetecc** [nginxinc/nginx-amplify-agent#74]
Hi, i just installed the agent on Centos 7 + nginx + Directadmin, amplify collects system data but not nginx stats.
These are the errors in agent.log

supervisor failed to read /etc/nginx/nginx.conf due to: IOError
nginx_meta nginx_meta failed to collect: find_packages raised ValueError

Thanks

**Comment by ptreyes** [comment]
Can you please reach out through Intercom chat so that we can identify you and create a support ticket? :) TIA!

**Comment by Zetecc** [comment]
I just did what you suggested, thanks.

**Comment by Beer786** [comment]
Hi Ptreyes,

I am also facing the same issue, I got system metric whereas i am not receiving Nginx metrics, Could you post  the suggestion here.

Thanks

**Comment by vmanikes** [comment]
I am also having the same issue on centos 7. Someone kindly reply

**Comment by kn007** [comment]
Same issue on centos 7

```
2018-03-27 21:53:21,154 [14787] nginx_meta additional info:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/amplify/agent/collectors/abstract.py", line 121, in collect
    method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/amplify/agent/collectors/nginx/meta.py", line 148, in find_packages
    package, version = rpm_out[0].split()
ValueError: too many values to unpack
```
