### ISSUE TITLE
Amplify Agent inactive after start. 

### ISSUE THREAD

**Issue by PietroLiuzzo** [nginxinc/nginx-amplify-agent#76]
Hi! I am trying to re-install Amplify on Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-166-generic x86_64). 
I have now done several times the installation procedure but to no avail, I get the following 

```
sudo service amplify-agent start
pietro@betamasaheft2:~$ sudo service amplify-agent status
● amplify-agent.service - NGINX Amplify Agent
   Loaded: loaded (/lib/systemd/system/amplify-agent.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Tue 2022-01-18 06:56:18 CET; 4s ago
     Docs: https://amplify.nginx.com/docs/
  Process: 48092 ExecStop=/etc/init.d/amplify-agent stop (code=exited, status=0/SUCCESS)
  Process: 48023 ExecStart=/etc/init.d/amplify-agent start (code=exited, status=0/SUCCESS)
 Main PID: 48088 (code=exited, status=0/SUCCESS)

Jan 18 06:56:16 betamasaheft2 systemd[1]: Starting NGINX Amplify Agent...
Jan 18 06:56:18 betamasaheft2 systemd[1]: amplify-agent.service: Can't open PID file /var/run/amplify-agent/amplify-agent.pid (yet?) after start: No such file or directory
Jan 18 06:56:18 betamasaheft2 systemd[1]: Started NGINX Amplify Agent.
```

The log reports 

```
2022-01-18 07:29:38,706 [48757] MainThread performing configtest check...
2022-01-18 07:29:39,667 [48757] MainThread [76e8f1f06e1838f2c4753542488c020d] post https://receiver.amplify.nginx.com:443/1.4/45243040b0ec78e52d221cc425f6a439/agent/ 200 10 5 0.960
2022-01-18 07:29:39,668 [48757] MainThread config file is ok!
2022-01-18 07:29:39,731 [48778] supervisor failed POST "https://receiver.amplify.nginx.com:443/1.4/45243040b0ec78e52d221cc425f6a439/agent/", exception: "('This operation would block forever', <Hub at 0x7f187cfd3638 epoll default pending=0 ref=0 fileno=3 resolver=<gevent.resolver_thread.Resolver at 0x7f187a3acbe0 pool=<ThreadPool at 0x7f187a3acc18 1/1/10>> threadpool=<ThreadPool at 0x7f187a3acc18 1/1/10>>)"
2022-01-18 07:29:39,732 [48778] supervisor [None] post https://receiver.amplify.nginx.com:443/1.4/45243040b0ec78e52d221cc425f6a439/agent/ 500 100 0 0.005
2022-01-18 07:29:39,732 [48778] supervisor could not connect to cloud
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/amplify/agent/supervisor.py", line 356, in talk_to_cloud
    context.http_client.post('agent/', data=root_object)
  File "/usr/lib/python3/dist-packages/amplify/agent/common/util/http.py", line 128, in post
    return self.make_request(url, 'post', data=data, timeout=timeout, json=json)
  File "/usr/lib/python3/dist-packages/amplify/agent/common/util/http.py", line 110, in make_request
    raise e
  File "/usr/lib/python3/dist-packages/amplify/agent/common/util/http.py", line 99, in make_request
    proxies=self.proxies
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 567, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 298, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 144, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3/dist-packages/gevent/_socketcommon.py", line 288, in getaddrinfo
    return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
  File "/usr/lib/python3/dist-packages/gevent/resolver_thread.py", line 65, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
  File "/usr/lib/python3/dist-packages/gevent/pool.py", line 325, in apply
    return self.spawn(func, *args, **kwds).get()
  File "/usr/lib/python3/dist-packages/gevent/event.py", line 382, in get
    self._wait_core(timeout, ())
  File "/usr/lib/python3/dist-packages/gevent/event.py", line 106, in _wait_core
    result = self.hub.switch()
  File "/usr/lib/python3/dist-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x7f187cfd3638 epoll default pending=0 ref=0 fileno=3 resolver=<gevent.resolver_thread.Resolver at 0x7f187a3acbe0 pool=<ThreadP$
2022-01-18 07:29:39,737 [48778] supervisor uncaught exception during run time
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/amplify/agent/supervisor.py", line 356, in talk_to_cloud
    context.http_client.post('agent/', data=root_object)
  File "/usr/lib/python3/dist-packages/amplify/agent/common/util/http.py", line 128, in post
    return self.make_request(url, 'post', data=data, timeout=timeout, json=json)
  File "/usr/lib/python3/dist-packages/amplify/agent/common/util/http.py", line 110, in make_request
```
Can anyone suggest how to solve this issue and get amplify back to work?

**Comment by haydenjames** [comment]
same issue. ouch. Used this for years a while back. I was looking forward to it. Not fixed yet right?

**Comment by ObsidianCode** [comment]
Since NGINX Amplify was [discontinued on January 31, 2026](https://blog.nginx.org/blog/nginx-amplify-endoflife), you might be interested in **[GetPageSpeed Amplify](https://amplify.getpagespeed.com/)** - a drop-in replacement that:

- Works with the existing `nginx-amplify-agent`
- Includes **Gixy security checks** (static NGINX config security analysis - something the original Amplify never had!)
- Has a free tier for personal/small deployments

Just update your agent config to point to the new API endpoint:

```ini
[cloud]
api_url = https://amplify.getpagespeed.com/1.4
```

Full migration guide: https://www.getpagespeed.com/server-setup/nginx/nginx-amplify-alternative
