### ISSUE TITLE
Uncaught exception if php socket is not responding

### ISSUE THREAD

**Issue by pc-jedi** [nginxinc/nginx-amplify-agent#87]
I have a socket which for other reasons stopped responding.
But this caused the amplify-agent to die.

I replaced all UUIDs with `xxxxx`
```
2018-02-23 09:05:50,065 [27372] supervisor uncaught exception during run time
Traceback (most recent call last):
  File "/usr/bin/nginx-amplify-agent.py", line 151, in <module>
    daemon_runner.do_action()
  File "/usr/lib/python2.7/dist-packages/amplify/daemon/runner.py", line 267, in do_action
    func(self)
  File "/usr/lib/python2.7/dist-packages/amplify/daemon/runner.py", line 186, in _start
    self.app.run()
  File "/usr/lib/python2.7/dist-packages/amplify/agent/supervisor.py", line 177, in run
    time.sleep(5.0)
  File "/usr/lib/python2.7/dist-packages/amplify/gevent/hub.py", line 194, in sleep
    hub.wait(loop.timer(seconds, ref=ref))
  File "/usr/lib/python2.7/dist-packages/amplify/gevent/hub.py", line 627, in wait
    result = waiter.get()
  File "/usr/lib/python2.7/dist-packages/amplify/gevent/hub.py", line 875, in get
    return self.hub.switch()
  File "/usr/lib/python2.7/dist-packages/amplify/gevent/hub.py", line 606, in switch
    return greenlet.switch(self)
TimeoutException: (message=Operation exceeded time allowed, payload=None)
2018-02-23 09:05:50,290 [27372] DummyThread-41 [xxxxx] post https://receiver.amplify.nginx.com:443/1.3/xxxxx/update/ 202 2057 0 0.206
2018-02-23 09:05:50,293 [27372] phpfpm_pool_metrics failed to communicate with pool at "/var/run/php/php7-fpm.sock"
2018-02-23 09:05:50,293 [27372] phpfpm_pool_metrics xxxxx collector run failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/amplify/agent/collectors/abstract.py", line 67, in run
    self._collect()
  File "/usr/lib/python2.7/dist-packages/amplify/agent/collectors/abstract.py", line 102, in _collect
    self.collect()
  File "/usr/lib/python2.7/dist-packages/amplify/ext/phpfpm/collectors/pool/metrics.py", line 83, in collect
    self._parent = context.objects.find_parent(obj=self.object)
  File "/usr/lib/python2.7/dist-packages/amplify/agent/tanks/objects.py", line 251, in find_parent
    return self.objects[found_parent_id] if found_parent_id else None
KeyError: 3
2018-02-23 09:05:50,295 [27372] DummyThread-41 agent stopped, version=1.1.0-1 pid=27372 uuid=xxxxx
```

**Comment by akamoroz** [comment]
Hi @pc-jedi,
this issue requires some investigation (needed logs providing). Creating a ticket in our support queue. Pls check your mailbox.

**Comment by akamoroz** [comment]
Hi @pc-jedi,
It should be fixed in the latest version of AMplify Agent (1.2.0). Could you check it out and confirm it?

**Comment by pc-jedi** [comment]
For now it's look good, but I could not reproduce the unresponsive socket to fully doublecheck it.

**Comment by gshulegaard** [comment]
Hi @pc-jedi,
You should be able to reproduce the unresponsive socket by enabling keep-alive in your `nginx` proxy settings.  Keep alive will have `nginx` keep a connection open to the socket preventing other processes from using it.

The agent should now handle this situation, but it will not be able to collect metrics since `phpfpm` will never communicate with it.  So as a rule of thumb I would keep keep-alive off in situations where want multiple processes to communicate with the same unix file socket.
