### ISSUE TITLE
MySQL Monitoring Issues when mysql host is diff from amplify host

### ISSUE THREAD

**Issue by cchandel** [nginxinc/nginx-amplify-agent#88]
Hi,
   I'm trying to monitor MySQL using amplify-agent v 1.1.0.
   In cases where the mysql host is diff from the host where amplify-agent is running, I face 2 problems as below.
1. I need to run a local mysqld process else I get an error.

> supervisor failed to find running mysqld via "ps xao pid,ppid,command | grep -P 'mysql[d]( |$)'" due to AmplifySubprocessError

Running a local mysqld process allows monitoring of the remote agent.

2. If I give a value to port (typically 3306)  I get this error.

> mysql_metrics failed to connect to MySQLd due to TypeError
> 2018-02-23 17:26:39,423 [15649] mysql_metrics additional info:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.1.0-py2.7.egg/amplify/ext/mysql/collectors/metrics.py", line 63, in mysql_status
>     c = pymysql.connect(**self.object.connection_args)  # these are coming from agent config for now
>   File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.1.0-py2.7.egg/amplify/pymysql/__init__.py", line 90, in Connect
>     return Connection(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.1.0-py2.7.egg/amplify/pymysql/connections.py", line 706, in __init__
>     self.connect()
>   File "/usr/lib/python2.7/site-packages/nginx_amplify_agent-1.1.0-py2.7.egg/amplify/pymysql/connections.py", line 922, in connect
>     self.host_info = "socket %s:%d" % (self.host, self.port)
> TypeError: %d format: a number is required, not str

   While I've got this going by experimenting with the values, the documentation needs to be updated and and these bugs fixed.
   Also, the amplify site needs links to the mysql documentation.
Thanks.

**Comment by akamoroz** [comment]
Hi @cchandel,
this issue requires some investigation. Creating a ticket in our support queue. Pls check your mailbox.

Also, the documentation will be updated soon.

**Comment by pdbreen** [comment]
Hi @akamoroz - any update on this?  I'm attempting to include monitoring of an Amazon RDS hosted instance, so there will be no local mysqld running.

**Comment by morales2k** [comment]
+1 

I am also getting a TypeError when attempting to connect to mysql via host/port instead of a socket.

I confirmed I can run the `show global status` query, but since the database is external, there must be something else going wrong.

The `/var/log/amplify-agent/agent.log` file has the following spammed all over it:

> 2018-05-17 15:31:35,062 [11917] mysql_metrics mysql_metrics failed to collect: mysql_status raised TypeError

Will be turning mysql extension to `False` while I can get more news on this.

Thanks in advance guys!

**Comment by gshulegaard** [comment]
Hey guys, thanks for the interest and taking the time to make reports!  The original MySQL extension was designed to monitor a locally running `mysqld` instance.  Given feedback and the collection involved, we are working on supporting remote monitoring, but I don't have an official timeline for it.

For now, you have to monitor `mysqld` with a locally running agent.  We will update here once we have remote support.

**Comment by morales2k** [comment]
Great news to learn that the team has this in their sights!  

What originally led me to believe remote monitoring of mysqld was already enabled was that the documentation has a commented setup for `host` and `port`. These are normally used when configuring a remote connection, so I just pasted my remote info for AWS RDS in there... alas... that isn't yet supported... 

This could benefit from a bit of further clarification in the docs.

**Comment by fnzv** [comment]
Is it possible to set host/port under amplify agent configuration?
I need to monitor an external MySQL host

**Comment by gshulegaard** [comment]
So we have implemented this feature but it is currently unreleased.  Unfortunately, I do not have a timeline for our next update to the Amplify agent at this time.

I will update here when it is available though.

**Comment by gabomasi** [comment]
Any news about this?

**Comment by bzikst** [comment]
Any updates?

**Comment by mikebronner** [comment]
We are seeing the following error when attempting to connect to a remote database:
```
2019-12-03 20:41:51,380 [5428] mysql_metrics mysql_metrics failed to collect: mysql_status raised KeyError 
```

Is this also possibly related to #102 ?

Thanks!
