### ISSUE TITLE
supervisor uncaught exception during run time

### ISSUE THREAD

**Issue by kn007** [nginxinc/nginx-amplify-agent#91]
system: CentOS 7 x64
nginx: 1.13.10
php: 7.2.3
mysql: 5.7.21
agent version: 1.1.0-1

A issue like: https://github.com/nginxinc/nginx-amplify-agent/issues/87

LOG:

```
2018-03-29 03:33:26,721 [26380] nginx_elog * collect in 0.000
2018-03-29 03:33:26,721 [26380] nginx_elog * processed 0 lines from file:/usr/local/nginx/logs/error.log
2018-03-29 03:33:26,721 [26380] nginx_elog * collect in 0.000
2018-03-29 03:33:26,721 [26380] mysql_meta * collect in 0.000
2018-03-29 03:33:26,874 [26380] supervisor uncaught exception during run time
Traceback (most recent call last):
  File "/usr/bin/nginx-amplify-agent.py", line 151, in <module>
    daemon_runner.do_action()
  File "/usr/lib/python2.7/site-packages/amplify/daemon/runner.py", line 267, in do_action
    func(self)
  File "/usr/lib/python2.7/site-packages/amplify/daemon/runner.py", line 186, in _start
    self.app.run()
  File "/usr/lib/python2.7/site-packages/amplify/agent/supervisor.py", line 177, in run
    time.sleep(5.0)
  File "/usr/lib/python2.7/site-packages/amplify/gevent/hub.py", line 194, in sleep
    hub.wait(loop.timer(seconds, ref=ref))
  File "/usr/lib/python2.7/site-packages/amplify/gevent/hub.py", line 627, in wait
    result = waiter.get()
  File "/usr/lib/python2.7/site-packages/amplify/gevent/hub.py", line 875, in get
    return self.hub.switch()
  File "/usr/lib/python2.7/site-packages/amplify/gevent/hub.py", line 606, in switch
    return greenlet.switch(self)
TimeoutException: (message=Operation exceeded time allowed, payload=None)
2018-03-29 03:33:26,926 [26380] DummyThread-50 modified payload; current payload stats: meta - 0, metrics - 1, events - 0, configs - 0
2018-03-29 03:33:26,975 [26380] DummyThread-50 {}
2018-03-29 03:33:26,975 [26380] DummyThread-50 [*] post https://receiver.amplify.nginx.com:443/1.3/*/update/ 202 638 0 0.049
2018-03-29 03:33:26,975 [26380] DummyThread-50 {'metrics': [*], 'configs': [], 'meta': [], 'events': []}
2018-03-29 03:33:26,975 [26380] DummyThread-50 finished flush_all; new payload stats: meta - 0, metrics - 0, events - 0, configs - 0
2018-03-29 03:33:26,975 [26380] DummyThread-50 skipping teardown of supervisor thread_id (id:140546142586832, name:DummyThread-50)
2018-03-29 03:33:26,976 [26380] DummyThread-50 skipping teardown of supervisor thread_id (id:140546142586832, name:DummyThread-50)
2018-03-29 03:33:26,976 [26380] DummyThread-50 stopping object "nginx" *
2018-03-29 03:33:26,976 [26380] nginx_config NginxConfigCollector collector for * received exit signal
2018-03-29 03:33:26,976 [26380] nginx_meta CentosNginxMetaCollector collector for * received exit signal
2018-03-29 03:33:26,976 [26380] nginx_metrics CentosNginxMetricsCollector collector for * received exit signal
2018-03-29 03:33:26,977 [26380] nginx_alog NginxAccessLogsCollector collector for * received exit signal
2018-03-29 03:33:26,977 [26380] nginx_alog NginxAccessLogsCollector collector for * received exit signal
2018-03-29 03:33:26,977 [26380] nginx_alog NginxAccessLogsCollector collector for * received exit signal
2018-03-29 03:33:26,977 [26380] nginx_alog NginxAccessLogsCollector collector for * received exit signal
2018-03-29 03:33:26,977 [26380] nginx_alog NginxAccessLogsCollector collector for * received exit signal
2018-03-29 03:33:26,977 [26380] nginx_alog NginxAccessLogsCollector collector for * received exit signal
2018-03-29 03:33:26,977 [26380] nginx_alog NginxAccessLogsCollector collector for * received exit signal
2018-03-29 03:33:26,977 [26380] nginx_alog NginxAccessLogsCollector collector for * received exit signal
2018-03-29 03:33:26,977 [26380] nginx_alog NginxAccessLogsCollector collector for * received exit signal
2018-03-29 03:33:26,978 [26380] nginx_alog NginxAccessLogsCollector collector for * received exit signal
2018-03-29 03:33:26,978 [26380] nginx_elog NginxErrorLogsCollector collector for * received exit signal
2018-03-29 03:33:26,978 [26380] nginx_elog NginxErrorLogsCollector collector for * received exit signal
2018-03-29 03:33:26,978 [26380] DummyThread-50 stopped object "nginx" *
2018-03-29 03:33:26,978 [26380] DummyThread-50 "nginx" object unregistered with ObjectsTank (id: 7, name: nginx 1.13.10 @ kn007.net)
2018-03-29 03:33:26,978 [26380] DummyThread-50 skipping teardown of supervisor thread_id (id:140546142586832, name:DummyThread-50)
2018-03-29 03:33:26,978 [26380] DummyThread-50 stopping object "phpfpm" *
2018-03-29 03:33:26,979 [26380] phpfpm_meta PHPFPMMetaCollector collector for * received exit signal
2018-03-29 03:33:26,979 [26380] phpfpm_metrics PHPFPMMetricsCollector collector for * received exit signal
2018-03-29 03:33:26,979 [26380] DummyThread-50 stopped object "phpfpm" *
2018-03-29 03:33:26,979 [26380] DummyThread-50 stopping object "phpfpm_pool" *
2018-03-29 03:33:26,979 [26380] phpfpm_pool_meta PHPFPMPoolMetaCollector collector for * received exit signal
2018-03-29 03:33:26,979 [26380] phpfpm_pool_metrics failed to communicate with pool at "/tmp/php-cgi.sock"
2018-03-29 03:33:26,980 [26380] phpfpm_pool_metrics additional info:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/amplify/ext/phpfpm/util/fpmstatus.py", line 130, in get_status
    resp = fcgi(self.env, lambda x, y: None)
  File "/usr/lib/python2.7/site-packages/amplify/agent/common/util/timeout.py", line 59, in decorated_view
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/amplify/ext/phpfpm/util/fcgi.py", line 126, in __call__
    inrec.read(sock)
  File "/usr/lib/python2.7/site-packages/amplify/flup/client/fcgi_app.py", line 193, in read
    raise EOFError
EOFError
2018-03-29 03:33:26,994 [26380] phpfpm_pool_metrics non-success returned by fcgi (status: 500)
2018-03-29 03:33:26,994 [26380] phpfpm_pool_metrics additional info:
  status: 500
  headers: []
  out:
  err:

2018-03-29 03:33:26,995 [26380] phpfpm_pool_metrics * collect in 60.153
2018-03-29 03:33:26,995 [26380] phpfpm_pool_metrics * collector run failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/amplify/agent/collectors/abstract.py", line 67, in run
    self._collect()
  File "/usr/lib/python2.7/site-packages/amplify/agent/collectors/abstract.py", line 102, in _collect
    self.collect()
  File "/usr/lib/python2.7/site-packages/amplify/ext/phpfpm/collectors/pool/metrics.py", line 83, in collect
    self._parent = context.objects.find_parent(obj=self.object)
  File "/usr/lib/python2.7/site-packages/amplify/agent/tanks/objects.py", line 251, in find_parent
    return self.objects[found_parent_id] if found_parent_id else None
KeyError: 8
2018-03-29 03:33:27,032 [26380] DummyThread-50 stopped object "phpfpm_pool" *
2018-03-29 03:33:27,032 [26380] DummyThread-50 "phpfpm_pool" object unregistered with ObjectsTank (id: 9, name: 9)
2018-03-29 03:33:27,032 [26380] DummyThread-50 "phpfpm" object unregistered with ObjectsTank (id: 8, name: phpfpm master @ kn007.net)
2018-03-29 03:33:27,032 [26380] DummyThread-50 stopping object "mysql" *
2018-03-29 03:33:27,032 [26380] mysql_meta MySQLMetaCollector collector for * received exit signal
2018-03-29 03:33:27,033 [26380] mysql_metrics MySQLMetricsCollector collector for * received exit signal
2018-03-29 03:33:27,033 [26380] DummyThread-50 stopped object "mysql" *
2018-03-29 03:33:27,033 [26380] DummyThread-50 "mysql" object unregistered with ObjectsTank (id: 10, name: mysql @ kn007.net)
2018-03-29 03:33:27,033 [26380] DummyThread-50 stopping object "system" *
2018-03-29 03:33:27,033 [26380] sys_meta CentosSystemMetaCollector collector for * received exit signal
2018-03-29 03:33:27,033 [26380] sys_metrics CentosSystemMetricsCollector collector for * received exit signal
2018-03-29 03:33:27,034 [26380] DummyThread-50 stopped object "system" *
2018-03-29 03:33:27,034 [26380] DummyThread-50 "system" object unregistered with ObjectsTank (id: 6, name: system @ kn007.net)
2018-03-29 03:33:27,034 [26380] DummyThread-50 agent stopped, version=1.1.0-1 pid=26380 uuid=*
```

**Comment by akamoroz** [comment]
Hi @kn007,

This issue requires some investigation because we have not got any debug logs from #87. Creating a special ticket in our support queue. Pls check your mailbox and provide logs for further investigation.

Thanks!

**Comment by kn007** [comment]
Thank you, @akamoroz
I will send you email with my log now.

**Comment by kn007** [comment]
[Ticket:7174] Fix.
