### ISSUE TITLE
Crashes agent on CentOS 7

### ISSUE THREAD

**Issue by germetist** [nginxinc/nginx-amplify-agent#98]
CentOS Linux release 7.4.1708 (Core)
nginx-amplify-agent-1.1.0-2.el7.x86_64

Amplify agent every time crashes with this output in the log

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/amplify/agent/collectors/abstract.py", line 67, in run
    self._collect()
  File "/usr/lib/python2.7/site-packages/amplify/agent/collectors/abstract.py", line 102, in _collect
    self.collect()
  File "/usr/lib/python2.7/site-packages/amplify/ext/phpfpm/collectors/pool/metrics.py", line 83, in collect
    self._parent = context.objects.find_parent(obj=self.object)
  File "/usr/lib/python2.7/site-packages/amplify/agent/tanks/objects.py", line 251, in find_parent
    return self.objects[found_parent_id] if found_parent_id else None
KeyError: 3
2018-04-05 14:50:04,779 [14282] DummyThread-11 agent stopped, version=1.1.0-1 pid=14282 uuid=ae8d29b176fe56428287312deb8327a9

**Comment by akamoroz** [comment]
Hi @germetist ,
Coul you try to update the agent to the latest version 1.2.0 and provide the results?

Thanks!
